const blue = '#4b7bec'
const lightGray = '#e4e7ed'
const darkGrayBlue = '#344861'
//const darkBackground = '#25242c'
const darkBackground = '#1c1c1e'

export const lightTheme = {
	themeName: 'light',
	background: '#f9fafb',
	primaryTextColor: darkGrayBlue,
	secondaryTextColor: '#9e9e9e',
	loginButtonBorderColor: darkGrayBlue,
	topbarBackgroundColor: 'white',
	topbarFontColor: darkGrayBlue,
	bookmarkOffColor: lightGray,
	bookmarkOnColor: blue,
	actionSheetButtonBackground: '#eeeef0',
	actionSheetCancelBackground: 'white',
	actionSheetButtonBorder: '#d8d8db',
	editButtonColor: blue,
	editButtonBackground: lightGray,
	numpadButtonBackground: lightGray,
	disabledButtonBackground: 'transparent', //#cccfd4
	disabledButtonBorderColor: 'transparent', //#cccfd4
	lockedButtonBackgroundColor: blue,
	lockedButtonBorderColor: blue,
	canvasLightDefaultCellColor: 'white',
	canvasDarkDefaultCellColor: '#e2ebf3',
	canvasCellBorderColor: '#bec6d4',
	canvasQuadrantBorderColor: darkGrayBlue,
	canvasClueColor: darkGrayBlue,
	canvasSolutionColor: blue,
	canvasSelectedCellBackground: '#bbdefb',
	canvasSameValueCellBackground: '#c3d7ea',
	canvasNoteHighlightColor: 'black',
	canvasAnimationBaseColor: '0, 0, 0',
	gameMenuListBackground: 'white',
	gameMenuListBorder: 'none',
	mobile__gameMenuListBorder: 'white',
	menuButtonBorderColor: lightGray,
	mobile__menuButtonBorderColor: lightGray,
	menuButtonColor: blue,
	mobile__menuButtonColor: blue,
	gameMenuListShadow: '0 5px 20px 0 rgb(0 0 0 / 20%)',
	menuButtonHoverColor: blue,
	menuButtonHoverBackground: '#e4eaf1',
	settingsItemBackground: 'white',
	settingsItemBorder: lightGray,
	settingsItemColor: darkGrayBlue,
	cancelButtonBackround: 'white',
	cancelButtonFontWeight: 'regular',
	modeSelectorBorderColor: darkGrayBlue,
	modeSelectorColor: darkGrayBlue,
	modeSelectorSelectedBorderColor: blue,
	canvasKillerCageColor: darkGrayBlue,
	homeGridShadow: '0px 0px 10px #aaaaaa',
	homeGridIconColor: '#444444',
}

export const darkTheme = {
	themeName: 'dark',
	background: 'black',
	primaryTextColor: 'white',
	secondaryTextColor: '#e0e0e0',
	loginButtonBorderColor: 'white',
	topbarBackgroundColor: 'transparent',
	topbarFontColor: 'white',
	bookmarkOffColor: 'darkgray',
	bookmarkOnColor: blue,
	actionSheetButtonBackground: '#1f1e1e',
	actionSheetCancelBackground: '#2c2c2e',
	actionSheetButtonBorder: '#434344',
	editButtonColor: '#75747c',
	editButtonBackground: darkBackground,
	numpadButtonBackground: darkBackground,
	disabledButtonBackground: 'transparent',
	disabledButtonBorderColor: '#25242c',
	lockedButtonBackgroundColor: blue,
	lockedButtonBorderColor: blue,
	canvasLightDefaultCellColor: '#25242c',
	canvasDarkDefaultCellColor: '#191925',
	canvasCellBorderColor: 'black',
	canvasQuadrantBorderColor: 'black',
	canvasClueColor: '#75747c',
	canvasSolutionColor: '#6f90c3',
	canvasSelectedCellBackground: '#153b79',
	canvasSameValueCellBackground: '#16151b',
	canvasNoteHighlightColor: 'white',
	canvasAnimationBaseColor: '255, 255, 255',
	gameMenuListBackground: '#25242c',
	gameMenuListBorder: 'solid 1px white',
	mobile__gameMenuListBorder: 'none',
	menuButtonBorderColor: 'white',
	mobile__menuButtonBorderColor: darkGrayBlue,
	menuButtonColor: '#75747c',
	mobile__menuButtonColor: blue,
	gameMenuListShadow: 'none',
	menuButtonHoverColor: 'white',
	menuButtonHoverBackground: '#25242c',
	settingsItemBackground: '#25242c',
	settingsItemBorder: 'black',
	settingsItemTitleColor: 'white',
	cancelButtonBackround: '#25242c',
	cancelButtonFontWeight: 'bold',
	modeSelectorBorderColor: 'white',
	modeSelectorColor: 'white',
	modeSelectorSelectedBorderColor: blue,
	canvasKillerCageColor: '#75747c',
	homeGridBackground: darkBackground,
	homeGridShadow: 'none',
	homeGridIconColor: '#616161',
}