const blue = '#4b7bec';
const lightGray = '#e4e7ed';
const darkGray = '#344861';
const darkBackground = '#25242c';

export const lightTheme = {
	themeName: 'light',
	background: 'white',
	loginButtonBorderColor: darkGray,
	navbarFontColor: darkGray,
	editButtonColor: blue,
	editButtonBackground: lightGray,
	numpadButtonBackground: lightGray,
	disabledButtonBackground: 'transparent', //#cccfd4
	disabledButtonBorderColor: 'transparent', //#cccfd4
	lockedButtonBackgroundColor: blue,
	lockedButtonBorderColor: blue,
	canvasLightDefaultCellColor: 'white',
	canvasDarkDefaultCellColor: '#e2ebf3',
	canvasCellBorderColor: '#bec6d4',
	canvasQuadrantBorderColor: darkGray,
	canvasClueColor: darkGray,
	canvasSolutionColor: blue,
	canvasSelectedCellBackground: '#bbdefb',
	canvasSameValueCellBackground: '#c3d7ea',
	canvasNoteHighlightColor: blue,
	canvasAnimationBaseColor: '0, 0, 0',
	gameMenuListBackground: 'white',
	gameMenuListBorder: 'none',
	mobile__gameMenuListBorder: 'white',
	menuButtonBorderColor: lightGray,
	mobile__menuButtonBorderColor: lightGray,
	menuButtonColor: blue,
	mobile__menuButtonColor: blue,
	gameMenuListShadow: '0 5px 20px 0 rgb(0 0 0 / 20%)',
	menuButtonHoverColor: blue,
	menuButtonHoverBackground: '#e4eaf1',
	settingsItemBackground: 'white',
	settingsItemBorder: lightGray,
	settingsItemColor: darkGray,
	cancelButtonBackround: 'white',
	cancelButtonFontWeight: 'regular',
	modalOverlayBackground: 'white',
	modeSelectorBorderColor: darkGray,
	modeSelectorColor: darkGray,
	modeSelectorSelectedBorderColor: blue,
	canvasKillerCageColor: darkGray,
};

export const darkTheme = {
	themeName: 'dark',
	background: '#171719',
	loginButtonBorderColor: 'white',
	navbarFontColor: 'white',
	editButtonColor: '#75747c',
	editButtonBackground: darkBackground,
	numpadButtonBackground: darkBackground,
	disabledButtonBackground: 'transparent',
	disabledButtonBorderColor: '#25242c',
	lockedButtonBackgroundColor: 'inherit',
	lockedButtonBorderColor: 'white',
	canvasLightDefaultCellColor: '#25242c',
	canvasDarkDefaultCellColor: '#191925',
	canvasCellBorderColor: 'black',
	canvasQuadrantBorderColor: 'black',
	canvasClueColor: '#75747c',
	canvasSolutionColor: '#6f90c3',
	canvasSelectedCellBackground: '#153b79',
	canvasSameValueCellBackground: '#16151b',
	canvasNoteHighlightColor: 'white',
	canvasAnimationBaseColor: '255, 255, 255',
	gameMenuListBackground: '#25242c',
	gameMenuListBorder: 'solid 1px white',
	mobile__gameMenuListBorder: 'none',
	menuButtonBorderColor: 'white',
	mobile__menuButtonBorderColor: darkGray,
	menuButtonColor: '#75747c',
	mobile__menuButtonColor: blue,
	gameMenuListShadow: 'none',
	menuButtonHoverColor: 'white',
	menuButtonHoverBackground: '#25242c',
	settingsItemBackground: '#25242c',
	settingsItemBorder: 'black',
	settingsItemTitleColor: 'white',
	cancelButtonBackround: '#25242c',
	cancelButtonFontWeight: 'bold',
	modalOverlayBackground: '#171719',
	modeSelectorBorderColor: 'white',
	modeSelectorColor: 'white',
	modeSelectorSelectedBorderColor: blue,
	canvasKillerCageColor: '#75747c',
};